### ISSUE TITLE
Problems running binaries on OSX

### ISSUE THREAD

**Issue by alejandrojapkin** [grrrr/py#8]
Binaries will not run in Pd-Extended, no matter installation path. OSX 10.9 Mavericks 64bit.
I do not understand why externals are being compiled universal when it's very clear that Pd only deals with 32bit objects.

**Comment by grrrr** [comment]
To troubleshoot your problems, a more detailed report would be needed. I would ask you to inquire on the Pd-list or the ext mailing list (http://grrrr.org/cgi-bin/mailman/listinfo/ext), since this is a developer, not a user platform.
As for the second part: 64-bit Pd needs 64-bit objects, and universal builds can contain both 32-bit und 64-bit objects. The dynamic linker will care about choosing the right one.
