### ISSUE TITLE
Not running under Anaconda py2.7 OSX

### ISSUE THREAD

**Issue by alejandrojapkin** [grrrr/py#9]
PyExt not running under Anaconda py2.7 OSX > 10.6 
Apparently is a well known issue. Has the system been tested by the developers on Mac? Is there a route to make it work?

**Comment by grrrr** [comment]
Not sure what the difference between Anaconda and a typically installed Python framework is.
py/pyext supports the system-default Python installation and the one from python.org.
I personally have used it with every OS from 10.3 to 10.11.

**Comment by alejandrojapkin** [comment]
Anaconda's notebook support is unmatched, as well as its integration with several NN tools. Furthermore, it's advised not to touch the default Python in OSX. Properly using PyExt would demand all the scikit tools. Anaconda is a widespread Python distribution very much used by scientists, just as Pure Data is. Why is this not considered a valid issue?

**Comment by grrrr** [comment]
It is certainly not a problem to modify the py/pyext build system so that it compiles for Anaconda, if this is even necessary at all. Probably not.
Anaconda users are encouraged to contribute a pull request for a more direct support, should it be necessary. For the context of Pure data, this is a niche issue and can not be maintained by the py/pyext developer.
